name: 'Check Commit SHA'
description: 'Checks if commit sha exist in repo'
inputs:
  commit:
    description: 'Commit ID'
    required: false
runs:
  using: "composite"
  steps:
    - name: 'Check Commit SHA'
      run: |
        git pull
        git branch -r
        if git cat-file -e ${{ inputs.commit }} ; then
          echo 'Commit exist'
        else
          echo 'Commit does not exist'
          exit 1
        fi
      shell: bash