name: Check Commit SHA
on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit ID
        required: true
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit SHA check
        uses: ./.github/actions/commit-hash-check
        with:
          commit: ${{ github.event.inputs.commit }}