name: Check Commit SHA
on: [push]
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit SHA check
        uses: ./.github/actions/commit-hash-check
        with:
          commit: '123434566'