name: telegram message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      run: |
        git checkout 12301o0525
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      if: failure()
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: The ${{ github.event_name }} ${{ github.ref }} event triggered first step.