name: telegram message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      run: |
        git checkout 12301o0525
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      if: failure()
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Working testing failed:\n
        Job: [ ${{ github.job }} ](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n
        Logs: [ ${{ github.run_id }} ](https://github.com/${{ github.repository }}/runs/${{ github.run_id }})\n
        Commit: [ ${{ github.sha }}(https://github.com/${{ github.repository }}/commit/${{ github.sha }})\n
        Branch: [ ${{ github.ref }} ](https://github.com/${{ github.repository }}/tree/${{ github.ref }})
        History: [commits](https://github.com/${{ github.repository }}/commits/${{ github.sha }})
        Triggered on: ${{ github.event_name }}
        Committer: ${{ github.actor }}
        "