name: Test Workflow Telegram Bot
on: [push]
jobs:
  telegram-bot-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/actions/commit-hash-check
        with:
          commit: 59bcab6
      - uses: ./.github/actions/configure_github_envs
        if: always()
#      - name: Checkout to commit hash
#        run: |
#          git commit 194911491949
      - name: Sending Message to Telegram Chat
        # we can give directory path that contains action.yaml or repo address in username/repository_name@version format
        # in our case it would be nashmaniac/create-issue-action@v1.0 where v1.0 is the version of action
        # for now we will give directory path. The directory must contain action.yaml
        uses: ./.github/actions/test-telegram
        # pass user input as arguments
        if: failure()
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_TO }}
          message: "🔴 Working testing failed:\n
          *Job*: [ ${{ github.job }} ](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n
          *Logs*: [ ${{ env.JOB_ID }} ](https://github.com/${{ github.repository }}/runs/${{ env.JOB_ID }})\n
          *Commit*: [ ${{ github.sha }} ](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\n
          *Branch*: [ ${{ env.BRANCH_NAME }} ](https://github.com/${{ github.repository }}/tree/${{ env.BRANCH_NAME }})\n
          *History*: [ commits ](https://github.com/${{ github.repository }}/commits/${{ github.sha }})\n
          *Triggered on*: ${{ github.event_name }}\n
          *Committer*: ${{ github.actor }}\n
          ---------------- Commit message -------------------
          "
          disable_web_page_preview: false