name: Test TypeScript Telegram Bot
on: [push]
jobs:
  telegram-bot-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Commit SHA
        uses: ./.github/actions/commit-hash-check
        with:
          commit: '123456'
#      - name: Add-ons for Telegram action
#        uses: ./.github/actions/configure_github_envs
#        if: always()
      - name: Sending Message to Telegram Chat
        uses: ./.github/actions/typescript-telegram-test
        if: failure()
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          to: ${{ secrets.TELEGRAM_TO }}
          parse_mode: MarkdownV2
          disable_web_page_preview: true
      - run: |
          echo ${{ env.BRANCH_NAME }}
          printenv
        if: failure()